---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-0
  labels:
    type: local
spec:
  #storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/vault-data-0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-vault-0
  labels:
    type: local
spec:
  #storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/vault-audit-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-1
  labels:
    type: local
spec:
  #storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/vault-data-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-vault-1
  labels:
    type: local
spec:
  #storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/vault-audit-1


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-2
  labels:
    type: local
spec:
  #storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/vault-data-2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-vault-2
  labels:
    type: local
spec:
  #storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/vault-audit-2
