kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: host-path-without-node-affinity-cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./resources.yaml
        containerPath: /kind/manifests/default-storage.yaml
      - hostPath: /opt/mnt/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
  - role: worker
    extraMounts:
      - hostPath: /opt/mnt/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
  - role: worker
    extraMounts:
      - hostPath: /opt/mnt/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
