---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-docker-registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.204
    path: "/kubernetes-shared/kube-test"
  mountOptions:
    - nfsvers=4.2
