apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-6dc63297-a91f-42a4-902b-5bc159eb094f
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test
    namespace: default
  hostPath:
    path: /var/local-path-provisioner/pvc-6dc63297-a91f-42a4-902b-5bc159eb094f_default_test
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lp-provisioner-example-worker
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
